app/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    re_path(r'^.*\.html', views.pages, name='pages'),

]

cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include  # add this
from patients.views import ajouter_patient, liste_patient, archiver_patient, afficher_detail_patient, liste_patient_archiver, supprimer_patient, desarchiver_patient, supprimer_patient, liste_patient_payees, liste_patient_non_payees
from rdvs.views import liste_rdv, modifier_rdv_from_planning, modifier_rdv, ajouter_rdv, confirmer_rdv, ajouter_patient_from_rdv, supprimer_rdv, list_rdv_toDay, list_rdv_week, list_rdv_month, ajouter_rdv_formulaire
from consultations.views import  ajouter_consultation, modifier_prix_consultation,  modifier_consultation, liste_consultation, formulaire_creation_consultation, liste_consultation_non_payees, liste_consultation_patient, supprimer_consultation, liste_consultation_payees, liste_consultation_patient_payees, liste_consultation_patient_non_payees
from fichesMedical.views import modifier_fiche_medical, modifier_contenu_fiche_medical, formulaire_creation_fiche_medical, liste_fiche_medical, ajouter_fiche_medical, supprimer_fiche_medical, afficher_fiche_medical
from diagnostiques.views import ajouter_diagnostique, afficher_diagnostique, formulaire_creation_diagnostique,  modifier_diagnostique_formulaire, supprimer_diagnostique
from medicaments.views import ajouter_medicament, liste_medicament, supprimer_medicament, modifier_medicament_formulaire, modifier_medicament
from radios.views import ajouter_radio, formulaire_ajout_radio, liste_radio, supprimer_radio,  afficher_radio_patient, afficher_radio
from traitements.views import formulaire_creation_traitement, ajouter_traitement, valider_traitement, annuler_traitement, supprimer_traitement
from payements.views import formulaire_creation_payement, ajouter_payement
from fournisseurs.views import ajouter_fournisseur, statistique, liste_fournisseur, supprimer_fournisseur
from achats.views import ajouter_achat, fourmulaire_ajout_achat, formulaire_payer_achat, payer_achat, supprimer_achat, imprimer_bon_commande, valider_bon_commande
from ordonances.views import formulaire_creation_ordonance, ajouter_ordonance, view_pdf, liste_ordonance, list_medicament_ordonance, supprimer_ordonance
from depenses.views import ajouter_depense, formulaire_ajouter_depense, supprimer_depense, formulaire_ajouter_depense_employee
from employes.views import ajouter_employee, liste_employe, supprimer_employe
from django.contrib.auth.decorators import login_required

from typerdvs.views import formulaire_ajout_type_rdv, ajouter_type_rdv, supprimer_type_rdv

urlpatterns = [
    path('admin/', admin.site.urls),  # Django admin route afficher_fiche_medical/
    path('customers/', include("customers.urls")),  # Django customers route
    path('', include('cal.urls')),
    path("", include("app.urls")),  # UI Kits Html files
    path("", include("authentication.urls")),  # Auth routes - login / register liste_consultation_patient
    path('ajouter_patient', ajouter_patient, name="ajouter_patient"),
    path('patients',liste_patient, name="patients"),
    path('rdvs', liste_rdv, name="rdvs"),
    path('ajouter_rdv', ajouter_rdv, name="ajouter_rdv"),
    path(r'^modifier_rdv/(?P<event_id>\d+)/$', modifier_rdv, name="modifier_rdv"),
    path('confirmer_rdv',confirmer_rdv, name="confirmer_rdv"),
    path('ajouter_patients_rdv',ajouter_patient_from_rdv, name="ajouter_patients_rdv"),
    path('archiver_patient',archiver_patient, name="archiver_patient"),
    path('supprimer_rdv',supprimer_rdv, name="supprimer_rdv"),
    path('afficher_detail_patient',afficher_detail_patient, name="afficher_detail_patient"),
    path('ajouter_consultation',ajouter_consultation, name="ajouter_consultation"),
    path('consultations',liste_consultation, name="consultations"),
    path('formulaire_creation_consultation',formulaire_creation_consultation, name='formulaire_creation_consultation'),
    path('liste_consultation_patient',liste_consultation_patient, name='liste_consultation_patient'),
    path('supprimer_consultation',supprimer_consultation, name='supprimer_consultation'),
    path('consultations_payees',liste_consultation_payees, name="consultations_payees"),
    path('liste_consultation_non_payees',liste_consultation_non_payees, name="liste_consultation_non_payees"),
    path('modifier_consultation',modifier_consultation, name="modifier_consultation"),
    path('modifier_prix_consultation',modifier_prix_consultation,name="modifier_prix_consultation"),
    path('formulaire_creation_fiche_medical',formulaire_creation_fiche_medical, name='formulaire_creation_fiche_medical'),
    path('fiches_medical',liste_fiche_medical, name='fiches_medical'),
    path('ajouter_fiche_medical',ajouter_fiche_medical, name="ajouter_fiche_medical"),
    path('supprimer_fiche_medical',supprimer_fiche_medical, name="supprimer_fiche_medical"),
    path('afficher_fiche_medical',afficher_fiche_medical, name='afficher_fiche_medical'),
    path('modifier_contenu_fiche_medical',modifier_contenu_fiche_medical, name="modifier_contenu_fiche_medical"),
    path('modifier_fiche_medical',modifier_fiche_medical, name="modifier_fiche_medical"),
    path('ajouter_diagnostique',ajouter_diagnostique, name="ajouter_diagnostique"),
    path('formulaire_creation_diagnostique',formulaire_creation_diagnostique, name="formulaire_creation_diagnostique"),
    path('liste_patient_archiver',liste_patient_archiver, name="liste_patient_archiver"),
    path('supprimer_patient/',supprimer_patient),
    path('desarchiver_patient',desarchiver_patient, name="desarchiver_patient"),
    path('afficher_diagnostique',afficher_diagnostique, name="afficher_diagnostique"),
    path('medicaments',liste_medicament, name="medicaments"),
    path('ajouter_medicaments',ajouter_medicament, name="ajouter_medicaments"),
    path('supprimer_medicament',supprimer_medicament, name="supprimer_medicament"),
    path('modifier_medicament_formulaire',modifier_medicament_formulaire, name="modifier_medicament_formulaire"),
    path('modifier_medicament',modifier_medicament, name="modifier_medicament"),
    path('formulaire_creation_ordonance',formulaire_creation_ordonance, name="formulaire_creation_ordonance"),
    path('ajouter_ordonance',ajouter_ordonance, name="ajouter_ordonance"),
    path('view_pdf',view_pdf, name="view_pdf"),
    path('liste_ordonance',liste_ordonance, name="liste_ordonance"),
    path('list_medicament_ordonance', list_medicament_ordonance, name="list_medicament_ordonance"),
    path('liste_consultation_patient_payees', liste_consultation_patient_payees, name="liste_consultation_patient_payees"),
    path('liste_consultation_patient_non_payees', liste_consultation_patient_non_payees, name="liste_consultation_patient_non_payees"),
    path('modifier_diagnostique_formulaire',  modifier_diagnostique_formulaire, name="modifier_diagnostique_formulaire"),
    path('list_rdv_toDay', list_rdv_toDay, name="list_rdv_toDay"),
    #list_rdv_week, list_rdv_month, formulaire_ajout_radio, lition_traitement
    path('list_rdv_week', list_rdv_week, name="list_rdv_week"),
    path('list_rdv_month', list_rdv_month, name="list_rdv_month"),
    path('supprimer_ordonance', supprimer_ordonance, name="supprimer_ordonance"),
    path('ajouter_radio', ajouter_radio, name="ajouter_radio"),
    path('formulaire_ajout_radio', formulaire_ajout_radio, name="formulaire_ajout_radio"),
    path('liste_radio', liste_radio, name="liste_radio"),
    path('supprimer_radio', supprimer_radio, name="supprimer_radio"),
    path('afficher_radio_patient', afficher_radio_patient, name="afficher_radio_patient"),
    #ajouter_traitement, valider_traitement, afficher_radio
    path('formulaire_creation_traitement', formulaire_creation_traitement, name="formulaire_creation_traitement"),
    path('ajouter_traitement', ajouter_traitement, name="ajouter_traitement"),
    path('valider_traitement', valider_traitement, name="valider_traitement"),
    path('annuler_traitement', annuler_traitement, name="annuler_traitement"),
    path('afficher_radio', afficher_radio, name="afficher_radio"),
    path('formulaire_creation_payement', formulaire_creation_payement, name="formulaire_creation_payement"),
    path('ajouter_payement', ajouter_payement, name="ajouter_payement"),
    path('ajouter_fournisseur', ajouter_fournisseur, name="ajouter_fournisseur"),
    path('statistique', statistique, name="statistique"),
    path('fourmulaire_ajout_achat', fourmulaire_ajout_achat, name="fourmulaire_ajout_achat"),
    path('ajouter_achat', ajouter_achat, name="ajouter_achat"),
    path('formulaire_payer_achat', formulaire_payer_achat, name="formulaire_payer_achat"),
    path('payer_achat', payer_achat, name="payer_achat"),
    path('supprimer_patient', supprimer_patient, name="supprimer_patient"),
    path('supprimer_diagnostique', supprimer_diagnostique, name="supprimer_diagnostique"),
    path('ajouter_depense', ajouter_depense, name="ajouter_depense"),
    path('formulaire_ajouter_depense', formulaire_ajouter_depense, name="formulaire_ajouter_depense"),
    path('supprimer_depense', supprimer_depense, name="supprimer_depense"),
    path('supprimer_achat', supprimer_achat, name="supprimer_achat"),
    path('ajouter_employee', ajouter_employee, name="ajouter_employee"),
    #formulaire_ajouter_depense
    path('formulaire_ajouter_depense_employee', formulaire_ajouter_depense_employee, name="formulaire_ajouter_depense_employee"),
    path('liste_patient_non_payees', liste_patient_non_payees, name="liste_patient_non_payees"),
    path('liste_patient_payees', liste_patient_payees, name="liste_patient_payees"),
    path('liste_fournisseur', liste_fournisseur, name="liste_fournisseur"),
    path('imprimer_bon_commande', imprimer_bon_commande, name="imprimer_bon_commande"),
    path('valider_bon_commande', valider_bon_commande, name="valider_bon_commande"),
    path('liste_employe', liste_employe, name="liste_employe"),

core/templates/includes/footer.html
    <footer class="footer section py-5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-lg-6 mb-4 mb-lg-0">
                    <p class="mb-0 text-center text-xl-left">
                        &copy; <a class="text-primary font-weight-normal" href="#" target="_blank"></a>
                        - coded by <a target="_blank" href="https://www.createdz.com/">Agence Create</a>
                    </p>
                </div>

                <div class="col-12 col-lg-6">
                    <!-- List -->
                    <ul class="list-inline list-group-flush list-group-borderless text-center text-xl-right mb-0">
                        <li class="list-inline-item px-0 px-sm-2">
                            <a target="_blank" 
                               href="https://www.createdz.com/">Agence Create</a>
                        </li>
                    </ul>
                    <!-- End List -->
                </div>
            </div>
        </div>
    </footer>

core/templates/includes/scripts.html
{% load static %}

<!-- Core -->
<script src="{% static 'assets/vendor/popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>

<!-- Vendor JS -->
<script src="{% static 'assets/vendor/onscreen/dist/on-screen.umd.min.js' %}"></script>

<!-- Slider -->
<script src="{% static 'assets/vendor/nouislider/distribute/nouislider.min.js' %}"></script>

<!-- Jarallax -->
<script src="{% static 'assets/vendor/jarallax/dist/jarallax.min.js' %}"></script>

<!-- Smooth scroll -->
<script src="{% static 'assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>

<!-- Count up -->
<script src="{% static 'assets/vendor/countup.js/dist/countUp.umd.js' %}"></script>

<!-- Notyf -->
<script src="{% static 'assets/vendor/notyf/notyf.min.js' %}"></script>
<script type="application/javascript" src="{% static 'assets/js/notify.js' %}"></script>
<script>
    {% if messages %}
        {% for message in messages %}
            notification['{{ message.tags }}']("<p>" + '{{ message|capfirst }}' + "</p>");
        {% endfor %}
    {% endif %}
</script>

<!-- Charts -->
<script src="{% static 'assets/vendor/chartist/dist/chartist.min.js' %}"></script>
<script src="{% static 'assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js' %}"></script>

<!-- Datepicker -->
<script src="{% static 'assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

<!-- Simplebar -->
<script src="{% static 'assets/vendor/simplebar/dist/simplebar.min.js' %}"></script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Volt JS -->
<script src="{% static 'assets/js/volt.min.js' %}"></script>

core/templates/includes/sidebar.html
{% load auth_extras %}
    <nav id="sidebarMenu" class="sidebar d-md-block bg-primary text-white collapse px-4">
        <div class="sidebar-sticky pt-3 mx-auto">
            <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
            <div class="d-flex align-items-center">
                <div class="user-avatar lg-avatar mr-4">
                <img src="/static/assets/img/team/profile-picture-3.jpg" class="card-img-top rounded-circle border-white" alt="Bonnie Green">
                </div>
                <div class="d-block">
                <h2 class="h6">
              
                    {{ request.user.username }}
                    
                </h2>
                <a href="{% url 'logout' %}" class="btn btn-secondary text-dark btn-xs">
                    <span class="mr-2"><span class="fas fa-sign-out-alt"></span></span>Sign Out</a>
                </div>
            </div>
            <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" class="fas fa-times" data-toggle="collapse"
                    data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
                    aria-label="Toggle navigation"></a>
            </div>
            </div>
            <ul class="nav flex-column">
                                 
            <li class="nav-item  {% if 'list_rdv' in segment %} active {% endif %}">
                <a href="{% url 'cal:calendar' %}" class="nav-link">
                <span class="sidebar-icon"><span class="far fa-calendar-alt"></span></span>
                <span>Planning </span>
                </a>
            </li>
           <!--  <li class="nav-item  {% if 'list_rdv' in segment %} active {% endif %}">
                <a href="{% url 'list_rdv_toDay' %}" class="nav-link">
                <span class="sidebar-icon"><span class="far fa-calendar-alt"></span></span>
                <span>Planning </span>
                </a>
            </li> -->
            <li class="nav-item  {% if 'rdvs' in segment %} active {% endif %}">
                <a href="{% url 'rdvs' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="far fa-calendar-check"></span></span>
                    <span>Rendez-vous</span>
                </a>
            </li>
             
            <li class="nav-item  {% if 'patients' in segment %} active {% endif %}">
                <a href="{% url 'patients'%}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-users"></span></span>
                    <span>Patients</span>
                </a>
            </li>
             <li class="nav-item  {% if 'fiches_medical' in segment %} active {% endif %}">
                <a href="{% url 'fiches_medical' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-file-medical"></span></span>
                    <span>Fiches medicales</span>
                </a>
            </li>
             {% if request.user|has_group:"dentiste" %}
                        <li class="nav-item  {% if 'consultations' in segment %} active {% endif %}">
                <a href="{% url 'consultations' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="far fa-file-alt"></span></span>
                    <span>Consultations
                    </span>
                </a>
            </li>
             {% endif %}
            {% if request.user|has_group:"dentiste" %}
            <li class="nav-item  {% if 'medicaments' in segment %} active {% endif %}">
                <a href="{% url 'medicaments' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-capsules"></span></span>
                    <span>Medicaments</span>
                </a>
            </li>
             {% endif %}
             {% if request.user|has_group:"dentiste" %}
             <li class="nav-item  {% if 'ordonances' in segment %} active {% endif %}">
                <a href="{% url 'liste_ordonance' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-file-medical-alt"></span></span>
                    <span>Ordonances</span>
                </a>
            </li>
            {% endif %}
             {% if request.user|has_group:"dentiste" %}
             <li class="nav-item  {% if 'radios' in segment %} active {% endif %}">
                <a href="{% url 'liste_radio' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-teeth"></span></span>
                    <span>Radios</span>
                </a>
            </li>
             {% endif %}
           

              {% if request.user|has_group:"dentiste" %}
             <li class="nav-item  {% if 'stat' in segment %} active {% endif %}">
                <a href="{% url 'statistique' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-chart-line"></span></span>
                    <span>Statistique</span>
                </a>
            </li>
            {% endif %}
           {% if request.user|has_group:"dentiste" %}
             <li class="nav-item  {% if 'fournisseur' in segment %} active {% endif %}">
                <a href="{% url 'liste_fournisseur' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-suitcase"></span></span>
                    <span>Fournisseurs</span>
                </a>
            </li>
             {% endif %}
          {% if request.user|has_group:"dentiste" %}

              <li class="nav-item  {% if 'employe' in segment %} active {% endif %}">
                <a href="{% url 'liste_employe' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-user-nurse"></span></span>
                    <span>Employés</span>
                </a>
            </li>
            {% endif %}
             <li class="nav-item  {% if 'profile' in segment %} active {% endif %}">
                <a href="{% url 'profile' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-cog"></span></span>
                    <span>Settings</span>
                </a>
            </li>
         <!--    <li class="nav-item">
                <span class="nav-link  collapsed  d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#submenu-app">
                <span>
                    <span class="sidebar-icon"><span class="fas fa-table"></span></span> 
                    Tables
                </span>
                <span class="link-arrow"><span class="fas fa-chevron-right"></span></span> 
                </span>
                <div class="multi-level collapse " role="list" id="submenu-app" aria-expanded="false">
                    <ul class="flex-column nav">
                        <li class="nav-item "><a class="nav-link" href="/bootstrap-tables.html"><span>Bootstrap Tables</span></a></li>
                    </ul>
                </div>
            </li> -->
           <!--  <li class="nav-item">
                <span class="nav-link  collapsed  d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#submenu-pages">
                <span>
                    <span class="sidebar-icon"><span class="far fa-file-alt"></span></span> 
                    Page examples
                </span>
                <span class="link-arrow"><span class="fas fa-chevron-right"></span></span> 
                </span>
                <div class="multi-level collapse " role="list" id="submenu-pages" aria-expanded="false">
                    <ul class="flex-column nav">
                        <li class="nav-item"><a class="nav-link" href="/sign-in.html"><span>Sign In</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/sign-up.html"><span>Sign Up</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/forgot-password.html"><span>Forgot password</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/reset-password.html"><span>Reset password</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/lock.html"><span>Lock</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/page-404.html"><span>404 Not Found</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="/page-500.html"><span>500 Server Error</span></a></li>
                    </ul>
                </div>
            </li> -->
           <!--  <li class="nav-item">
                <span class="nav-link  collapsed  d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#submenu-components">
                <span>
                    <span class="sidebar-icon"><span class="fas fa-box-open"></span></span> 
                    Components
                </span>
                <span class="link-arrow"><span class="fas fa-chevron-right"></span></span> 
                </span>
                <div class="multi-level collapse " role="list" id="submenu-components" aria-expanded="false">
                    <ul class="flex-column nav">
                        <li class="nav-item "><a class="nav-link" href="/ui-buttons.html"><span>Buttons</span></a></li>
                        <li class="nav-item "><a class="nav-link" href="/ui-notifications.html"><span>Notifications</span></a></li>
                        <li class="nav-item "><a class="nav-link" href="/ui-forms.html"><span>Forms</span></a></li>
                        <li class="nav-item "><a class="nav-link" href="/ui-modals.html"><span>Modals</span></a></li>
                        <li class="nav-item "><a class="nav-link" href="/ui-typography.html"><span>Typography</span></a></li>
                    </ul>
                </div>
                <i class="fas fa-user-plus"></i>
            </li> -->
                       
            <li role="separator" class="dropdown-divider mt-4 mb-3 border-black"></li>

            {% if request.user|has_group:"dentiste" %}
             <li class="nav-item">
                <a href="{% url 'register' %}" class="nav-link d-flex align-items-center">
                <span class="sidebar-icon">
                   <span class="fas fa-user-plus text-info"></span>
                </span>
                <span class="mt-1">Ajouter infermiére</span>
                </a>
            </li>
            {% endif%}

            <li class="nav-item">
                <a href="/" class="nav-link d-flex align-items-center">
                <span class="sidebar-icon">
                    <img src="/static/assets/img/brand/dental-presentation-blue.png" height="40" width="40" alt="Dental Logo">
                </span>
                <span class="mt-1">Presentation</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-sign-out-alt text-danger"></span></span>
                    <span>Logout</span>
                </a>
            </li> 
           <!--  <li class="nav-item">
                <a target="_blank" 
                   href="https://github.com/app-generator/django-user-profile" class="nav-link d-flex align-items-center">
                <span class="sidebar-icon">
                    <span class="fas fa-download"></span>
                </span>
                <span class="mt-1">Source Code</span>
                </a>
            </li>  -->           
           <!--  <li class="nav-item">
                <a target="_blank"
                   href="https://themesberg.com/product/django/volt-admin-dashboard-pro" class="nav-link d-flex align-items-center">
                    <span class="sidebar-icon"><span class="fas fa-rocket text-danger"></span></span>
                    <span>PRO Version</span>
                </a>
            </li> -->
            </ul>
        </div>
    </nav>