app/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    re_path(r'^.*\.html', views.pages, name='pages'),

]

cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include  # add this
from patients.views import ajouter_patient, liste_patient, archiver_patient, afficher_detail_patient, liste_patient_archiver, supprimer_patient, desarchiver_patient, supprimer_patient, liste_patient_payees, liste_patient_non_payees
from rdvs.views import liste_rdv, modifier_rdv_from_planning, modifier_rdv, ajouter_rdv, confirmer_rdv, ajouter_patient_from_rdv, supprimer_rdv, list_rdv_toDay, list_rdv_week, list_rdv_month, ajouter_rdv_formulaire
from consultations.views import  ajouter_consultation, modifier_prix_consultation,  modifier_consultation, liste_consultation, formulaire_creation_consultation, liste_consultation_non_payees, liste_consultation_patient, supprimer_consultation, liste_consultation_payees, liste_consultation_patient_payees, liste_consultation_patient_non_payees
from fichesMedical.views import modifier_fiche_medical, modifier_contenu_fiche_medical, formulaire_creation_fiche_medical, liste_fiche_medical, ajouter_fiche_medical, supprimer_fiche_medical, afficher_fiche_medical
from diagnostiques.views import ajouter_diagnostique, afficher_diagnostique, formulaire_creation_diagnostique,  modifier_diagnostique_formulaire, supprimer_diagnostique
from medicaments.views import ajouter_medicament, liste_medicament, supprimer_medicament, modifier_medicament_formulaire, modifier_medicament
from radios.views import ajouter_radio, formulaire_ajout_radio, liste_radio, supprimer_radio,  afficher_radio_patient, afficher_radio
from traitements.views import formulaire_creation_traitement, ajouter_traitement, valider_traitement, annuler_traitement, supprimer_traitement
from payements.views import formulaire_creation_payement, ajouter_payement
from fournisseurs.views import ajouter_fournisseur, statistique, liste_fournisseur, supprimer_fournisseur
from achats.views import ajouter_achat, fourmulaire_ajout_achat, formulaire_payer_achat, payer_achat, supprimer_achat, imprimer_bon_commande, valider_bon_commande
from ordonances.views import formulaire_creation_ordonance, ajouter_ordonance, view_pdf, liste_ordonance, list_medicament_ordonance, supprimer_ordonance
from depenses.views import ajouter_depense, formulaire_ajouter_depense, supprimer_depense, formulaire_ajouter_depense_employee
from employes.views import ajouter_employee, liste_employe, supprimer_employe
from django.contrib.auth.decorators import login_required

from typerdvs.views import formulaire_ajout_type_rdv, ajouter_type_rdv, supprimer_type_rdv

urlpatterns = [
    path('admin/', admin.site.urls),  # Django admin route afficher_fiche_medical/
    path('customers/', include("customers.urls")),  # Django customers route
    path('', include('cal.urls')),
    path("", include("app.urls")),  # UI Kits Html files
    path("", include("authentication.urls")),  # Auth routes - login / register liste_consultation_patient
    path('ajouter_patient', ajouter_patient, name="ajouter_patient"),
    path('patients',liste_patient, name="patients"),
    path('rdvs', liste_rdv, name="rdvs"),
    path('ajouter_rdv', ajouter_rdv, name="ajouter_rdv"),
    path(r'^modifier_rdv/(?P<event_id>\d+)/$', modifier_rdv, name="modifier_rdv"),
    path('confirmer_rdv',confirmer_rdv, name="confirmer_rdv"),
    path('ajouter_patients_rdv',ajouter_patient_from_rdv, name="ajouter_patients_rdv"),
    path('archiver_patient',archiver_patient, name="archiver_patient"),
    path('supprimer_rdv',supprimer_rdv, name="supprimer_rdv"),
    path('afficher_detail_patient',afficher_detail_patient, name="afficher_detail_patient"),
    path('ajouter_consultation',ajouter_consultation, name="ajouter_consultation"),
    path('consultations',liste_consultation, name="consultations"),
    path('formulaire_creation_consultation',formulaire_creation_consultation, name='formulaire_creation_consultation'),
    path('liste_consultation_patient',liste_consultation_patient, name='liste_consultation_patient'),
    path('supprimer_consultation',supprimer_consultation, name='supprimer_consultation'),
    path('consultations_payees',liste_consultation_payees, name="consultations_payees"),
    path('liste_consultation_non_payees',liste_consultation_non_payees, name="liste_consultation_non_payees"),
    path('modifier_consultation',modifier_consultation, name="modifier_consultation"),
    path('modifier_prix_consultation',modifier_prix_consultation,name="modifier_prix_consultation"),
    path('formulaire_creation_fiche_medical',formulaire_creation_fiche_medical, name='formulaire_creation_fiche_medical'),
    path('fiches_medical',liste_fiche_medical, name='fiches_medical'),
    path('ajouter_fiche_medical',ajouter_fiche_medical, name="ajouter_fiche_medical"),
    path('supprimer_fiche_medical',supprimer_fiche_medical, name="supprimer_fiche_medical"),
    path('afficher_fiche_medical',afficher_fiche_medical, name='afficher_fiche_medical'),
    path('modifier_contenu_fiche_medical',modifier_contenu_fiche_medical, name="modifier_contenu_fiche_medical"),
    path('modifier_fiche_medical',modifier_fiche_medical, name="modifier_fiche_medical"),
    path('ajouter_diagnostique',ajouter_diagnostique, name="ajouter_diagnostique"),
    path('formulaire_creation_diagnostique',formulaire_creation_diagnostique, name="formulaire_creation_diagnostique"),
    path('liste_patient_archiver',liste_patient_archiver, name="liste_patient_archiver"),
    path('supprimer_patient/',supprimer_patient),
    path('desarchiver_patient',desarchiver_patient, name="desarchiver_patient"),
    path('afficher_diagnostique',afficher_diagnostique, name="afficher_diagnostique"),
    path('medicaments',liste_medicament, name="medicaments"),
    path('ajouter_medicaments',ajouter_medicament, name="ajouter_medicaments"),
    path('supprimer_medicament',supprimer_medicament, name="supprimer_medicament"),
    path('modifier_medicament_formulaire',modifier_medicament_formulaire, name="modifier_medicament_formulaire"),
    path('modifier_medicament',modifier_medicament, name="modifier_medicament"),
    path('formulaire_creation_ordonance',formulaire_creation_ordonance, name="formulaire_creation_ordonance"),
    path('ajouter_ordonance',ajouter_ordonance, name="ajouter_ordonance"),
    path('view_pdf',view_pdf, name="view_pdf"),
    path('liste_ordonance',liste_ordonance, name="liste_ordonance"),
    path('list_medicament_ordonance', list_medicament_ordonance, name="list_medicament_ordonance"),
    path('liste_consultation_patient_payees', liste_consultation_patient_payees, name="liste_consultation_patient_payees"),
    path('liste_consultation_patient_non_payees', liste_consultation_patient_non_payees, name="liste_consultation_patient_non_payees"),
    path('modifier_diagnostique_formulaire',  modifier_diagnostique_formulaire, name="modifier_diagnostique_formulaire"),
    path('list_rdv_toDay', list_rdv_toDay, name="list_rdv_toDay"),
    #list_rdv_week, list_rdv_month, formulaire_ajout_radio, lition_traitement
    path('list_rdv_week', list_rdv_week, name="list_rdv_week"),
    path('list_rdv_month', list_rdv_month, name="list_rdv_month"),
    path('supprimer_ordonance', supprimer_ordonance, name="supprimer_ordonance"),
    path('ajouter_radio', ajouter_radio, name="ajouter_radio"),
    path('formulaire_ajout_radio', formulaire_ajout_radio, name="formulaire_ajout_radio"),
    path('liste_radio', liste_radio, name="liste_radio"),
    path('supprimer_radio', supprimer_radio, name="supprimer_radio"),
    path('afficher_radio_patient', afficher_radio_patient, name="afficher_radio_patient"),
    #ajouter_traitement, valider_traitement, afficher_radio
    path('formulaire_creation_traitement', formulaire_creation_traitement, name="formulaire_creation_traitement"),
    path('ajouter_traitement', ajouter_traitement, name="ajouter_traitement"),
    path('valider_traitement', valider_traitement, name="valider_traitement"),
    path('annuler_traitement', annuler_traitement, name="annuler_traitement"),
    path('afficher_radio', afficher_radio, name="afficher_radio"),
    path('formulaire_creation_payement', formulaire_creation_payement, name="formulaire_creation_payement"),
    path('ajouter_payement', ajouter_payement, name="ajouter_payement"),
    path('ajouter_fournisseur', ajouter_fournisseur, name="ajouter_fournisseur"),
    path('statistique', statistique, name="statistique"),
    path('fourmulaire_ajout_achat', fourmulaire_ajout_achat, name="fourmulaire_ajout_achat"),
    path('ajouter_achat', ajouter_achat, name="ajouter_achat"),
    path('formulaire_payer_achat', formulaire_payer_achat, name="formulaire_payer_achat"),
    path('payer_achat', payer_achat, name="payer_achat"),
    path('supprimer_patient', supprimer_patient, name="supprimer_patient"),
    path('supprimer_diagnostique', supprimer_diagnostique, name="supprimer_diagnostique"),
    path('ajouter_depense', ajouter_depense, name="ajouter_depense"),
    path('formulaire_ajouter_depense', formulaire_ajouter_depense, name="formulaire_ajouter_depense"),
    path('supprimer_depense', supprimer_depense, name="supprimer_depense"),
    path('supprimer_achat', supprimer_achat, name="supprimer_achat"),
    path('ajouter_employee', ajouter_employee, name="ajouter_employee"),
    #formulaire_ajouter_depense
    path('formulaire_ajouter_depense_employee', formulaire_ajouter_depense_employee, name="formulaire_ajouter_depense_employee"),
    path('liste_patient_non_payees', liste_patient_non_payees, name="liste_patient_non_payees"),
    path('liste_patient_payees', liste_patient_payees, name="liste_patient_payees"),
    path('liste_fournisseur', liste_fournisseur, name="liste_fournisseur"),
    path('imprimer_bon_commande', imprimer_bon_commande, name="imprimer_bon_commande"),
    path('valider_bon_commande', valider_bon_commande, name="valider_bon_commande"),
    path('liste_employe', liste_employe, name="liste_employe"),

cal/models.py
from django.db import models
from django.urls import reverse
from rdvs.models import Rdv


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    rdv = models.ForeignKey(Rdv, on_delete=models.CASCADE, null=True, blank=True)

    @property
    def get_html_url(self):
        if(self.rdv):
            url = reverse('modifier_rdv', args=(self.id,))
        else:
            url = reverse('cal:event_edit', args=(self.id,))


        

        return f'<a  href="{url}"> {self.title} </a>'

cal/forms.py
from django.forms import ModelForm, DateInput
from cal.models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

cal/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm

def index(request):
    return HttpResponse('hello')

class CalendarView(generic.ListView):
    model = Event
    template_name = 'calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))

    print(request)
    return render(request, 'event.html', {'form': form})

cal/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>


<title>
    Dentiste App - {% block title %}{% endblock %} | Pour votre cabinet dentaire
</title>




  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <!-- Fontawesome -->
<link type="text/css" href="/static/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">

<!-- Notyf -->
<link type="text/css" href="/static/assets/vendor/notyf/notyf.min.css" rel="stylesheet">

<!-- Volt CSS -->
<link type="text/css" href="/static/assets/css/volt.css" rel="stylesheet">

    <!-- Specific Page CSS goes HERE  -->
    {% block stylesheets %}{% endblock stylesheets %}


</head>
<body>


    <nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-md-none">
        <a class="navbar-brand mr-lg-5" href="/">
            <img class="navbar-brand-dark" src="/static/assets/img/brand/dental-presentation-blue.png" alt="Dentist App - Django" /> <img class="navbar-brand-light" src="/static/assets/img/brand/dental-presentation-blue.png" alt="Dentiste App" />
        </a>
        <div class="d-flex align-items-center">
            <button class="navbar-toggler d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>

    <div class="container-fluid bg-soft">
        <div class="row">
            <div class="col-12">

                {% include 'includes/sidebar.html' %}



  

  {% block content %}
  {% endblock %}
 </div>
        </div>
    </div>
     {% include 'includes/scripts.html' %}   

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
 {% block javascripts %}{% endblock javascripts %}


</body>
</html>

cal/templates/calendar.html
{% extends 'base.html' %}

{% block title %} Palnning {% endblock %} 

{% block content %}
 <main class="content">
 	 {% include 'includes/navigation.html' %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}">Le Mois Précédent </a>
	<a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Le Mois Prochain </a>
	<a class="btn btn-info right" href="{% url 'cal:event_new' %}"> Nouveau RDV </a>
</div>

{{ calendar }}

        {% include 'includes/footer.html' %}
  </main>

{% endblock content %}

 {% include 'includes/footer.html' %}
 {% block javascripts %}{% endblock javascripts %}

cal/templates/event.html
{% extends 'base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Planning </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Saungarder </button></td></tr>
  </table>
</form>
{% endblock %}